[report]
out = ["Html"]

[test_config]
# The name of the project or the configuration.
name = "tarpaulin"

manifest-path = "./Cargo.toml"

# Force a clean step before building the project.
# This will clean the target directory before running tests.
force-clean = false

# Skip the clean step and proceed without cleaning the target directory.
skip-clean = true

# Enable verbose logging for user information during tests.
verbose = false

# Count hits for coverage, useful for more detailed reporting.
count = true

# Set the type of coverage to be run:
# - 'line' for line coverage (default)
# - 'branch' for branch coverage
line-coverage = true
branch-coverage = false

# Directory to output coverage files and reports.
output-dir = "./.test_coverage"

# Build all packages in the workspace.
workspace = true

# Flag to allow the process to stop immediately on a test failure.
no-fail-fast = false

# Fail if coverage is below the specified threshold (e.g., 80.0).
# fail-under = null

# Colouring of logs in the terminal output (e.g., "auto", "always", "never").
color = "Auto"

# Number of jobs (threads) to use for building the tests.
# jobs = null
#
# Specify the engine to use for collecting coverage (default: "trace").
# engine = "Llvm"

# Include test functions in the coverage statistics.
include-tests = true

# Fail immediately after a single test fails.
fail-immediately = false

# Log to stderr instead of the default output.
stderr = false
