services:
  db:
    image: postgres:16-alpine
    container_name: parabellum_db
    restart: always
    environment:
      - POSTGRES_USER=parabellum
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=parabellum_dev
    ports:
      - "5432:5432"
    volumes:
      - parabellum_data:/var/lib/postgresql/data

  parabellum:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://parabellum:password@db:5432/parabellum_dev
      TEST_DATABASE_URL: postgres://parabellum:password@db:5432/parabellum_test
      RUST_LOG: info
    ports:
      - "8080:8080"

volumes:
  parabellum_data:
