[alias]
t = "test"

tt = "test -q -- --test-threads=1"

# coverage tests
tc = "cargo tarpaulin -p parabellum_server  -- --test-threads=1"

# show output
# t1nocap = "test -- --test-threads=1 --nocapture"
